server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: jwt-validation-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# Configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Informações da aplicação para o endpoint /actuator/info
info:
  app:
    name: ${spring.application.name}
    description: ${project.description:API para validação de JSON Web Tokens}
    version: ${project.version:0.0.1-SNAPSHOT}
    encoding: ${project.build.sourceEncoding:UTF-8}
    java:
      version: ${java.version:21}

# Configurações de logging
logging:
  level:
    io.github.bapadua.jwt: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 