server:
  port: 8090

spring:
  application:
    name: jwt-validation-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


# Configurações de logging
logging:
  level:
    io.github.bapadua.jwt: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 