name: Lambda Deploy

on:
  push:
    paths:
      - 'aws-lambda-jwt/**'
      - 'jwt-validation-lib/**'
      - 'terraform/lambda-simple/**'
      - 'pom.xml'
    branches: [ main ]
  workflow_dispatch:  # Permite execução manual

env:
  JAVA_VERSION: '21'
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: jwt-validator
  TERRAFORM_VERSION: '1.6.0'

jobs:
  deploy:
    name: Deploy Lambda Infrastructure & Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        
    - name: Install Parent POM
      run: |
        echo "📦 Instalando Parent POM..."
        mvn clean install -N -B
        echo "✅ Parent POM instalado"
        
    - name: Build JWT Validation Library
      run: |
        echo "📦 Construindo JWT Validation Library..."
        cd jwt-validation-lib
        mvn clean install -DskipTests -B
        echo "✅ JWT Validation Library construída"
        
    - name: Build Lambda package
      run: |
        echo "📦 Construindo pacote Lambda..."
        cd aws-lambda-jwt
        mvn clean package -DskipTests -B
        
        # Verifica se o JAR foi criado
        if ls target/aws-lambda-jwt-*.jar 1> /dev/null 2>&1; then
            echo "✅ Lambda JAR criado com sucesso"
            JAR_SIZE=$(stat -c%s target/aws-lambda-jwt-*.jar)
            echo "📦 Tamanho do JAR: $(echo "$JAR_SIZE" | awk '{printf "%.1f MB", $1/1024/1024}')"
        else
            echo "❌ Erro: Lambda JAR não foi criado"
            exit 1
        fi
        
    - name: Terraform Init
      run: |
        echo "🏗️ Inicializando Terraform..."
        cd terraform/lambda-simple
        terraform init
        
    - name: Terraform Plan
      run: |
        echo "📋 Planejando mudanças no Terraform..."
        cd terraform/lambda-simple
        terraform plan -detailed-exitcode
      continue-on-error: true
      
    - name: Cleanup existing resources (if any)
      run: |
        echo "🧹 Verificando e removendo recursos existentes..."
        cd terraform/lambda-simple
        
        # Verifica se a função jwt-validator existe
        if aws lambda get-function --function-name jwt-validator >/dev/null 2>&1; then
          echo "⚠️ Função jwt-validator já existe. Removendo para evitar conflito..."
          
          # Remove Function URL se existir
          aws lambda delete-function-url-config --function-name jwt-validator 2>/dev/null || echo "Function URL não encontrada"
          
          # Remove a função
          aws lambda delete-function --function-name jwt-validator 2>/dev/null || echo "Falha ao remover função"
          
          echo "✅ Função removida com sucesso"
        else
          echo "ℹ️ Função jwt-validator não existe. Continuando..."
        fi
      
    - name: Terraform Apply
      run: |
        echo "🚀 Aplicando infraestrutura Terraform..."
        cd terraform/lambda-simple
        terraform apply -auto-approve
        
        # Captura outputs importantes
        echo "📤 Obtendo outputs do Terraform..."
        FUNCTION_URL=$(terraform output -raw lambda_function_url 2>/dev/null || echo "not_available")
        echo "🔗 Function URL: $FUNCTION_URL"
        echo "FUNCTION_URL=$FUNCTION_URL" >> $GITHUB_ENV
        
    - name: Deploy Lambda Code
      run: |
        echo "📦 Verificando se precisa fazer deploy do código Lambda..."
        
        # Verifica se a função existe
        if aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} > /dev/null 2>&1; then
            echo "✅ Função Lambda encontrada, fazendo update do código..."
            cd aws-lambda-jwt
            
            # Encontra o JAR criado
            LAMBDA_JAR=$(ls target/aws-lambda-jwt-*.jar 2>/dev/null | head -n 1)
            echo "🚀 Fazendo deploy: $LAMBDA_JAR"
            
            # Update Lambda function code
            aws lambda update-function-code \
              --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
              --zip-file fileb://$LAMBDA_JAR
              
            # Wait for update to complete
            aws lambda wait function-updated \
              --function-name ${{ env.LAMBDA_FUNCTION_NAME }}
              
            echo "✅ Código Lambda atualizado com sucesso!"
        else
            echo "ℹ️ Função Lambda não existe ou foi criada pelo Terraform com o código já incluído"
            echo "ℹ️ Pulando update separado do código..."
        fi
        
    - name: Test Lambda function
      run: |
        echo "🧪 Testando função Lambda..."
        
        # Cria arquivo temporário com payload de teste
        echo '{"token": "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiNzg0MSIsIk5hbWUiOiJUb25pbmhvIEFyYXVqbyJ9.QY05sIjtrcJnP533kQNk8QXcaleJ1Q01jWY_ZzIZuAg"}' > test-payload.json
        
        # Test with valid JWT
        aws lambda invoke \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --payload file://test-payload.json \
          --cli-binary-format raw-in-base64-out \
          response.json
          
        echo "📋 Resposta do Lambda:"
        cat response.json
        
        # Verifica se a resposta contém "valid"
        if grep -q '"valid"' response.json; then
            echo "✅ Lambda respondendo corretamente"
        else
            echo "⚠️ Resposta do Lambda pode estar inesperada"
        fi
        
        # Limpa arquivo temporário
        rm test-payload.json
        
    - name: Test Function URL
      run: |
        echo "🌐 Testando Function URL..."
        
        if [ "$FUNCTION_URL" != "not_available" ]; then
            echo "🔗 Function URL: $FUNCTION_URL"
            
            # Test via HTTP with valid JWT
            echo "🧪 Testando com JWT válido..."
            curl -X POST "$FUNCTION_URL" \
              -H "Content-Type: application/json" \
              -d '{"token": "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJTZWVkIjoiNzg0MSIsIk5hbWUiOiJUb25pbmhvIEFyYXVqbyJ9.QY05sIjtrcJnP533kQNk8QXcaleJ1Q01jWY_ZzIZuAg"}' \
              -w "\n📊 Status: %{http_code}\n" \
              -s | jq '.' || echo "Resposta não é JSON"
              
            echo ""
            echo "🧪 Testando com JWT inválido..."
            curl -X POST "$FUNCTION_URL" \
              -H "Content-Type: application/json" \
              -d '{"token": "invalid-token"}' \
              -w "\n📊 Status: %{http_code}\n" \
              -s | jq '.' || echo "Resposta não é JSON"
        else
            echo "⚠️ Function URL não disponível do output do Terraform"
        fi
        
    - name: Deployment Summary
      run: |
        echo "## 🎉 Resumo do Deploy" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Infraestrutura**: Criada/Atualizada via Terraform" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Função Lambda**: Deploy realizado e testada" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Function URL**: Disponível para requisições HTTP" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "$FUNCTION_URL" != "not_available" ]; then
            echo "🔗 **Function URL**: $FUNCTION_URL" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Comandos de Teste:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo 'curl -X POST '"$FUNCTION_URL"' \' >> $GITHUB_STEP_SUMMARY
        echo '  -H "Content-Type: application/json" \' >> $GITHUB_STEP_SUMMARY
        echo '  -d '\''{"token": "SEU_JWT_TOKEN"}'\''' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        
    - name: 🎉 Success Notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        custom_payload: |
          {
            "channel": "#deploys",
            "username": "GitHub Actions",
            "icon_emoji": ":rocket:",
            "attachments": [{
              "color": "good",
              "title": "🎉 JWT Lambda Deploy - SUCCESS",
              "fields": [
                {
                  "title": "Repository",
                  "value": "${{ github.repository }}",
                  "short": true
                },
                {
                  "title": "Branch",
                  "value": "${{ github.ref_name }}",
                  "short": true
                },
                {
                  "title": "Commit", 
                  "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                  "short": true
                },
                {
                  "title": "Function URL",
                  "value": "${{ env.FUNCTION_URL }}",
                  "short": false
                }
              ],
              "footer": "Deployed successfully! 🚀",
              "ts": ${{ github.event.head_commit.timestamp }}
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: ❌ Failure Notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        custom_payload: |
          {
            "channel": "#deploys",
            "username": "GitHub Actions",
            "icon_emoji": ":x:",
            "attachments": [{
              "color": "danger",
              "title": "❌ JWT Lambda Deploy - FAILED",
              "fields": [
                {
                  "title": "Repository",
                  "value": "${{ github.repository }}",
                  "short": true
                },
                {
                  "title": "Branch", 
                  "value": "${{ github.ref_name }}",
                  "short": true
                },
                {
                  "title": "Commit",
                  "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                  "short": true
                },
                {
                  "title": "Logs",
                  "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>",
                  "short": false
                }
              ],
              "footer": "Deploy failed - check logs for details 🔍",
              "ts": ${{ github.event.head_commit.timestamp }}
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 