# ========================================
# Exemplos de Notificações para Deploy
# ========================================
# Este arquivo contém exemplos de como implementar
# diferentes tipos de notificações. 
# Copie e cole no workflow principal conforme necessário.

name: Notification Examples (REFERENCE ONLY)

# Este workflow não executa automaticamente
on:
  workflow_dispatch:
    inputs:
      notification_type:
        description: 'Tipo de notificação para testar'
        required: true
        type: choice
        options:
        - slack
        - discord
        - teams
        - email
        - telegram

jobs:
  # ========================================
  # 📱 SLACK NOTIFICATION
  # ========================================
  slack-example:
    if: github.event.inputs.notification_type == 'slack'
    runs-on: ubuntu-latest
    steps:
    - name: Slack Success
      uses: 8398a7/action-slack@v3
      with:
        status: success
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        custom_payload: |
          {
            "text": "🎉 Deploy concluído com sucesso!",
            "attachments": [{
              "color": "good",
              "fields": [
                {"title": "Projeto", "value": "JWT Lambda", "short": true},
                {"title": "Branch", "value": "${{ github.ref_name }}", "short": true}
              ]
            }]
          }

  # ========================================
  # 🎮 DISCORD NOTIFICATION  
  # ========================================
  discord-example:
    if: github.event.inputs.notification_type == 'discord'
    runs-on: ubuntu-latest
    steps:
    - name: Discord Success
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "JWT Lambda Deploy"
        description: "🚀 Deploy realizado com sucesso!"
        color: 0x00ff00
        username: "GitHub Actions"
        avatar_url: "https://github.com/actions.png"

  # ========================================
  # 💼 MICROSOFT TEAMS
  # ========================================
  teams-example:
    if: github.event.inputs.notification_type == 'teams'
    runs-on: ubuntu-latest
    steps:
    - name: Teams Success
      uses: skitionek/notify-microsoft-teams@master
      with:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}

  # ========================================
  # 📧 EMAIL NOTIFICATION
  # ========================================
  email-example:
    if: github.event.inputs.notification_type == 'email'
    runs-on: ubuntu-latest
    steps:
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚀 JWT Lambda Deploy - SUCCESS"
        to: dev-team@empresa.com
        from: github-actions@empresa.com
        html_body: |
          <h2>🎉 Deploy Concluído!</h2>
          <p><strong>Repositório:</strong> ${{ github.repository }}</p>
          <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
          <p><strong>Commit:</strong> ${{ github.sha }}</p>
          <p><strong>Status:</strong> ✅ Sucesso</p>

  # ========================================
  # 📱 TELEGRAM NOTIFICATION
  # ========================================
  telegram-example:
    if: github.event.inputs.notification_type == 'telegram'
    runs-on: ubuntu-latest
    steps:
    - name: Telegram Success
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🚀 *JWT Lambda Deploy - SUCCESS*
          
          📁 *Repo:* `${{ github.repository }}`
          🌿 *Branch:* `${{ github.ref_name }}`
          📝 *Commit:* `${{ github.sha }}`
          
          ✅ Deploy realizado com sucesso!
        format: markdown

# ========================================
# CONFIGURAÇÃO DOS SECRETS NECESSÁRIOS
# ========================================
# 
# Para Slack:
# - SLACK_WEBHOOK_URL
#
# Para Discord:  
# - DISCORD_WEBHOOK
#
# Para Teams:
# - TEAMS_WEBHOOK
#
# Para Email:
# - EMAIL_USERNAME
# - EMAIL_PASSWORD
#
# Para Telegram:
# - TELEGRAM_BOT_TOKEN
# - TELEGRAM_CHAT_ID 